import type { Metadata } from "next";
import { createAdminClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import { PageContainer } from "@/components/layout/PageContainer";
import { EvidenceIntelligenceClient } from "./EvidenceIntelligenceClient";

export async function generateMetadata({
  params,
}: {
  params: { id: string };
}): Promise<Metadata> {
  const { id } = await params;
  return {
    title: `Evidence Report SF-${id.split("-")[0].toUpperCase().slice(0, 8)} — SecureFlow AI`,
    description: "Detailed digital evidence intelligence report generated by the SecureFlow Rule Engine.",
  };
}

export default async function EvidenceReportPage({
  params,
}: {
  params: { id: string };
}) {
  const { id } = await params;

  // Lightweight existence check — full data loading is handled client-side
  // via /api/evidence/[id] to enable real-time re-run and mutations
  const supabase = await createAdminClient();
  const { data, error } = await supabase
    .from("analyses")
    .select("id")
    .eq("id", id)
    .single();

  if (error || !data) {
    console.error("Evidence not found:", id, error);
    notFound();
  }

  return (
    <PageContainer>
      <EvidenceIntelligenceClient analysisId={id} />
    </PageContainer>
  );
}
